### ISSUE TITLE
Retrieving list data from a paginated resopnse

### ISSUE THREAD

**Issue by samifall** [tonyhb/tectonic#104]
Hi,
I'm trying to getList data from a paginated response through SuperAgent.
my list response is formatted:
{
"count": total number of returned object,
"next": null,
"previous": null,
"results":[the list of objects]
}

Is there a way to configure SuperAgent to understand the above format.

thanks.

**Comment by samifall** [comment]
solved it through ( transform: data =>)

**Comment by tonyhb** [comment]
Yeah transforms are the right way to go here;  unfortunately there's no "standard" way of formatting API results and I totally agree that it's great to have metadata included in the response body.
