### ISSUE TITLE
Populate array of objects

### ISSUE THREAD

**Issue by j-lnaddef** [tonyhb/tectonic#111]
Let us say my JSON returns something like : 

`{
    "status": "success",
    "data": {
           "object": "value",
           "list": [
                  {
                         // some objects
                  }
            ]
     }
}`

The `//some objects` are pretty important and I create a model for them, called `ObjectModel`

How should I write my model file so my list of objects get populated properly?

The only thing I can think of is the following but this does not let me reference the model I create for my object.
`static fields = { id: '', status: '',
	data: { object: '', list: [] }
  };`

I would like to do something like that but it does not appear to be good syntax:
`static fields = { id: '', status: '',
	data: { object: '', list: ObjectModel[] }
  };`

I did not see anything similar in the examples provided.

**Comment by tonyhb** [comment]
You should be able to add a transform function to your source definition to
return the correct data:

https://tonyhb.github.io/tectonic/api-source-definitions.html
