### ISSUE TITLE
More granular tectonic Query Statuses

### ISSUE THREAD

**Issue by rrarunan** [tonyhb/tectonic#16]
Right now the Query Statuses have just a string for each state:

`Query(Model: team, Fields: *, Params: {}, Body: undefined, QueryType: GET), ReturnType: list):"SUCCESS"` 

Instead of a simple string, it would be good to have something like:

```
// { type: 'SUCCESS', status: '200', message: '' }
// { type: 'ERROR', status: '404', message: 'Object not found: <blah id>' }
// { type: 'ERROR', status: '500', message: 'Internal server error' }
// { type: 'ERROR', status: '400', message: 'The name of that thing should this' }
```

**Comment by tonyhb** [comment]
Fixed via status classes
