### ISSUE TITLE
Create model fails with no source definition found in some cases

### ISSUE THREAD

**Issue by rrarunan** [tonyhb/tectonic#50]
Scenario:
I have a model/spec, that I use to `create` an item. But, the structure of the object that is returned is different. 

`CreateUserSpec` -> create model with tectonic -> 201 created/200 ok -> response is `User` object.

So, if I use the sourcedef, `returnType`-> `User.item()`, I get the:
```
baseResolver.js:41 There is no source definition which resolves the query Query(Model: userCreateSpec, Fields: *, Params: {}, Body: {"Name":"test-net4","Role":"view-only", ReturnType: )
```

**Comment by tonyhb** [comment]
Fixed using .query in 1.3/2.0: http://tonyhb.github.io/tectonic/queries-side-effects.html

You no longer need a model to specify body values :)
