### ISSUE TITLE
load decorator causing React.PropTypes validation warnings

### ISSUE THREAD

**Issue by slightlytyler** [tonyhb/tectonic#60]
Currently using in a 15.x.x project and receiving `Warning: You are manually calling a React.PropTypes validation...` on components wrapper with the `load` decorator. Took a brief look into the src but couldn't see where this is happening. Probably worth upgrading React to the latest when fixing this issue.

**Comment by tonyhb** [comment]
Ah, thanks. Will chuck this into master in a sec and add this as a point release. React 15 stops you from accessing PropTypes directly, and we provided a shortcut for this within each model.  Easy fix landing today :)

**Comment by tonyhb** [comment]
@slightlytyler 2.0.2 with this is released :)
