### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by andreyluiz** [tonyhb/tectonic#76]
Tony, comparing the startup guide in the [site](https://tonyhb.github.io/tectonic/guide-setup.html) and the README, it seems to me that README is very outdated. For example, in README me nothing is mentioned about registering the tectonic in the reducers.

Which of the guides I can follow?

**Comment by tonyhb** [comment]
Yeah, the readme is intended to be an introduction to what tectonic does
for you, not necessarily a full guide.

I can see that's confusing, so sorry about that. Will add an issue to
update the readme with a link to the full setup guide to make things better.

That plus an example project should make things much easier to get started

**Comment by tonyhb** [comment]
So, to be clear: the site has a full getting started guide which should be
everything you need :)

**Comment by tonyhb** [comment]
Welcome!
