### ISSUE TITLE
Sideloading Data

### ISSUE THREAD

**Issue by matthewconstantine** [tonyhb/tectonic#82]
We're looking for a way to support sideloaded data that our API returns. So far we've made a custom driver that allows us to pass params to our API like `/posts?include[]=creators.`. That in turn returns a payload in the shape of:

```js
{
  posts: [{
    title: …,
    creator: 111,
    …
  }],
  users: [{
    id: 111,
    …
  }]
}
```

Our models associate `post.creator` with users. And we have a custom transform in our sources that returns `response.body.posts`. So two questions:

1) How do we store and consume the other models returned?
2) How would we cache those models?

Ideally a subsequent query to users like `users.getItem({ id: 111 }),` would return the cached result from the original response. 

One idea we're considering... perhaps could we dispatch the sideloaded data into the store with a query key that matches what we know a subsequent query would be looking for? If so, where in tectonic would we put that logic?

**Comment by tonyhb** [comment]
This is totally possible, I'll write documentation for a source definition that returns multiple models soon.

From 2.2.0 you can also set custom cache properties for sources and models.

One of the problems with side loading data is staleness (or freshness depending on your outlook on uh, life).  If you request this API endpoint and it returns many models of data, how long do you want to keep that in your store?   Do you need to refetch every time etc?

From 2.2.0 you can define TTLs in your sources:

```
{
  // side-loaded data - a polymorphic source that returns many models
  returns: {
    posts: Post.list(),
    users: User.list(),
  },
  cacheFor: 600, // cache all API data for 600 seconds, unless models have lower TTLs
  ...
}
```
